### ISSUE TITLE
kind `CustomResourceDefinition` is not validated against schema

### ISSUE THREAD

**Issue by eyarz** [yannh/kubeconform#100]
I took this YAML example for creating a CRD from the [official K8s doc](https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/):
```yaml
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: crontabs.stable.example.com
spec:
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                cronSpec:
                  type: string
                image:
                  type: string
                replicas:
                  type: integer
  scope: Namespaced
  names:
    plural: crontabs
    singular: crontab
    kind: CronTab
    shortNames:
    - ct
```
When validating this YAML with kubeconform I'm getting the following error:
```
...failed validation: could not find schema for CustomResourceDefinition
```
Although the schema exists on the `kubernetes-json-schema` repo:
https://github.com/yannh/kubernetes-json-schema/blob/master/v1.18.0/customresourcedefinition-apiextensions-v1.json

<img width="1094" alt="image" src="https://user-images.githubusercontent.com/19731161/160835029-46137a83-f7d4-4c6b-a316-0c33e23fc7e2.png">

Copying the schema from the repo and passing it with the `-schema-location` flag works fine, so I guess the issue is when trying to parse the kind type...

<img width="1001" alt="image" src="https://user-images.githubusercontent.com/19731161/160836482-6e538d2c-9d7a-4c39-ab80-4ccc3e861389.png">
