### ISSUE TITLE
Should a resource with an empty name be accepted?

### ISSUE THREAD

**Issue by PawelLipski** [yannh/kubeconform#122]
Each of the following is accepted by`kubeconform`:

```yaml
apiVersion: v1
kind: Secret
metadata:
  name:
---
apiVersion: v1
kind: Secret
metadata:
---
apiVersion: v1
kind: Secret
```

But I'm getting, as expected, `from server for: "....yaml": resource name may not be empty` from k8s server :/
