### ISSUE TITLE
kubeconform fails validation on null/empty fields

### ISSUE THREAD

**Issue by mustafaStakater** [yannh/kubeconform#124]
**Problem Description:**
We are using a kubeconform to validate manifests generated as a Helm chart in our pipelines. We are using mongodb helm chart that generated a few empty / null fields in a Deployment and Service as below
![Screenshot from 2022-08-24 18-04-38](https://user-images.githubusercontent.com/101177975/186587622-260cf58e-8de9-4475-aaf3-99bee796b4e7.png)
![Screenshot from 2022-08-24 18-05-22](https://user-images.githubusercontent.com/101177975/186588074-ba9118a6-e029-4aa6-91c7-f00177903156.png)

When I run kubeconform validation 
```
kubeconform -summary -schema-location "$location" /kubeconform-data/manifest.yaml    
```

It fails with following error:
![Screenshot from 2022-08-24 18-09-13](https://user-images.githubusercontent.com/101177975/186587680-e5ca1633-9480-44d5-9a18-21b1dcc1f781.png)

This seems weird because while making resources in openshift/kubernetes empty/fields are replaced by defaults and resources are created successfully. We intended to use this in our pipelines for validation, but this makes it unusable since nulls/ empty fields can occur quite frequently.

**Comment by eyarz** [comment]
I tried to reproduce this error with the following config (`nodePort: null`):
```yaml
apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    app.kubernetes.io/name: MyApp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9376
      nodePort: null
```
As you can see here, Kubeconform is passing:
![image](https://user-images.githubusercontent.com/19731161/186590033-8fe46dc9-968b-49c6-b1ae-083849a6c438.png)

I see that you're using `-schema-location "$location"` so maybe this is why I get a different result.
which schema do you use there to validate your manifest?
