### ISSUE TITLE
Add time to testcases for junit output

### ISSUE THREAD

**Issue by hodorrodoh** [yannh/kubeconform#127]
### Context

* kubeconform version: `v0.4.14`

Our team is leveraging kubeconform within [buildkite pipelines](https://buildkite.com/docs) to perform validations and then integrating with [test analytics](https://buildkite.com/docs/test-analytics).

However when running kubeconform with the `--output-type` as `junit` the output xml is not recognized as valid xml when uploading results to test analytics.

Upon comparing successful xml uploads in test analytics we have discovered that the kubeconform`testcase`'s do not include a `time` field which causes the error.

### How to reproduce

example yaml to run kubeconform with:
```yaml
---
# Source: upstream/charts/podinfo/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: release-name-podinfo
  labels:
    helm.sh/chart: podinfo-6.1.8
    app.kubernetes.io/name: release-name-podinfo
    app.kubernetes.io/version: "6.1.8"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 9898
      targetPort: http
      protocol: TCP
      name: http
    - port: 9999
      targetPort: grpc
      protocol: TCP
      name: grpc
  selector:
    app.kubernetes.io/name: release-name-podinfo
```
kubeconform command we are running
```sh
kubeconform --summary  --strict \
--kubernetes-version 1.22.9 \
--skip Role \
--output junit \
--ignore-missing-schemas \
example.yaml > example.xml
```
exported xml file
```xml
<testsuites name="kubeconform" time="0.164877018" tests="1" failures="0" disabled="0" errors="0">
  <testsuite name="podinfo.yaml" id="1" tests="1" failures="0" errors="0" disabled="0" skipped="0">
    <properties></properties>
    <testcase name="release-name-podinfo" classname="Service@v1"></testcase>
  </testsuite>
</testsuites>
```

- upload results to test analytics (if you have access) using [test collector plugin](https://github.com/buildkite-plugins/test-collector-buildkite-plugin)
or 
- to directly access test collector api (if you have access) [without the plugin](https://buildkite.com/docs/test-analytics/importing-json#how-to-import-json-in-buildkite-without-a-plugin)

the error test analytics sends back is 
```
{"id":"some-id","run_id":"run-id","queued":0,"skipped":1,"errors":["Invalid JUnit XML"],"run_url":"https://buildkite.com/analytics/runs
```

### Valid XML for test analytics

the snippet below can be successfully uploaded to test analytics
```xml
<testsuites name="kubeconform" time="0.164877018" tests="1" failures="0" disabled="0" errors="0">
  <testsuite name="podinfo.yaml" id="1" tests="1" failures="0" errors="0" disabled="0" skipped="0">
    <properties></properties>
    <testcase name="release-name-podinfo" classname="Service@v1" time="0.000"></testcase>
  </testsuite>
</testsuites>
```

Happy to help where I can. If you do not have access to buildkite we can test in our environment as well.
