### ISSUE TITLE
Adding support to autoscaling/v2beta2

### ISSUE THREAD

**Issue by arthurhenrique** [yannh/kubeconform#129]
how can I add autoscaling/v2beta2 this resources?

**Comment by birdx0810** [comment]
I'm also getting an error for HorizontalPodAutoscaler suggesting that it could not find schema.
(and PodDisruptionBudget and PodSecurityPolicy.

**Comment by arthurhenrique** [comment]
> You don't need to add it because it's already supported... Are you getting an error when trying to run kubeconform against HPA objects?

yes im gettting error, because seems not support v2beta

**Comment by yannh** [comment]
Hello! Are you validating your manifests against the correct kubernetes version - see the -kubernetes-version  parameter? Could you maybe add a file to this ticket with a command line on how to reproduce?

**Comment by arthurhenrique** [comment]
of course, follows bellow

file:
```
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: xpto
  labels:
    app: xpto
    owner: 'team-xpto'
spec:
  minReplicas: 15
  maxReplicas: 80
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: xpto
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 100
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
```

runs:

```sh
$ kubeconform x.yaml
```
