### ISSUE TITLE
Invalid Deployment is validated successfully

### ISSUE THREAD

**Issue by Blackclaws** [yannh/kubeconform#132]
Considering the following deployment:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service
spec:
  selector:
    matchLabels:
      app: service-fail
  template:
    metadata:
      labels:
        app: service
    spec:
      containers:
      - name: service
        image: <Image>
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "2560Mi"
            cpu: "5"
        ports:
          - name: http
            containerPort: 8080
```

This will fail to validate in kubernetes as the matchLabels do not match the template labels. However kubeconform accepts this deployment.
