### ISSUE TITLE
openapi2json.py silently fails when using "version" instead of "versions"

### ISSUE THREAD

**Issue by michohl** [yannh/kubeconform#159]
When running `openapi2jsonschema.py` on a CRD that doesn't contain a versions key it will silently fail.

I'm using the following as an example (referred to as `test.yml`)

```yaml
apiVersion: example.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: foo.bar.io
  annotations:
    "helm.sh/resource-policy": keep
spec:
  group: asdf.io
  version: v1
  scope: Namespaced
  names:
    plural: foos
    singular: foo
    kind: Foo
    shortNames:
    - fo
```

If I run the script with this file I get the following behavior:

```
(.venv) $ ./kubeconform/scripts/openapi2jsonschema.py test.yml
(.venv) $ echo $?
0
```

I believe this is caused by our spec above not including a `versions` key since it's using `version` instead. So it fails out of the [original if condition ](https://github.com/yannh/kubeconform/blob/84afe70659ab20a11a8a1273ac14e0e31af5ccbf/scripts/openapi2jsonschema.py#L149)but it is also not using `validation` so we fail [the elif condition](https://github.com/yannh/kubeconform/blob/84afe70659ab20a11a8a1273ac14e0e31af5ccbf/scripts/openapi2jsonschema.py#L169) as well which means we end up doing nothing with the entire file.

I'm hoping either `openapi2jsonschema.py` could be modified to respect a singular version as specified in my example or if that is not possible then at least the script will present an error and a non-zero exit code for the user.
