### ISSUE TITLE
Support KRM input

### ISSUE THREAD

**Issue by aabouzaid** [yannh/kubeconform#160]
Kubeconform could be used as a plugin in [Kustomize](https://github.com/kubernetes-sigs/kustomize) (it's built into `kubectl` since v1.14)

All needed is just support [KRM](https://github.com/kubernetes-sigs/kustomize/blob/master/cmd/config/docs/api-conventions/functions-spec.md) as input to Kubeconform.

I will create a PR for you if the feature is accepted.

**Comment by yannh** [comment]
Can you describe the implementation you have in mind? It would need a new flag to specify that the stdin input is in a different format, and a new output format to output the resource again? I m not against it in principle but i feel this might be non trivial to implement? Could you describe how this could work? Thanks! ❤️

**Comment by aabouzaid** [comment]
Hi Yann :wave: 

I'm thinking in a simpler impelmentation where Kubeconform will detect the type of STDIN, and if it's `ResourceList`, it will process the values of the `items` key as files.

I already did something similar for [SopsSecretGenerator](https://github.com/goabout/kustomize-sopssecretgenerator/blob/2d9fcf0e09e0f3b54eb4b99a83ce1d97f1efcd42/SopsSecretGenerator.go#L94)
```
apiVersion: config.kubernetes.io/v1
kind: ResourceList
metadata:
  name: krm-function-input
items:
- apiVersion: goabout.com/v1beta1
  kind: SopsSecretGenerator
  metadata:
    annotations:
      config.kubernetes.io/function: |
        exec:
          path: SopsSecretGenerator
      config.kubernetes.io/local-config: 'true'
      config.k8s.io/id: '1'
    name: secret-from-file
  disableNameSuffixHash: true
  files:
    - testdata/file.txt
- apiVersion: goabout.com/v1beta1
  kind: SopsSecretGenerator
  metadata:
    annotations:
      config.kubernetes.io/function: |
        exec:
          path: SopsSecretGenerator
      config.kubernetes.io/local-config: 'true'
      config.k8s.io/id: '2'
    name: secret-from-env
  disableNameSuffixHash: true
  envs:
    - testdata/vars.env
```
