### ISSUE TITLE
Could not find schema for VolumeSnapshot

### ISSUE THREAD

**Issue by carolili** [yannh/kubeconform#183]
Hello and thanks for creating a great tool for validating :)

I was trying to validate a very simple Kubernetes [VolumeSnapshot](https://kubernetes.io/docs/concepts/storage/volume-snapshots/) resource with v.1.25.8 manifests (`-kubernetes-version 1.25.8`) and it fails with `could not find schema for VolumeSnapshot`. Indeed, I can't seem to find any `VolumeSnapshot` schemas in the [kubernetes-json-schema](https://github.com/yannh/kubernetes-json-schema) repo. Was it not yet added or is there a reason it's not there? Perhaps I'm missing something?

Example resource:
```
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: my-snapshot
  namespace: testing
spec:
  source:
    persistentVolumeClaimName: pvc-test
```
