### ISSUE TITLE
Validate duplicate evar in deployment, pod, job, cronjob spec

### ISSUE THREAD

**Issue by suryapandian** [yannh/kubeconform#188]
Any `kind` of kubernetes resource with a container could have environment variables with duplicates.
Kubeconform validation on the environment variables, finding duplicates and throwing an error at duplciates would be helpful.

```yaml
---
apiVersion: batch/v1
kind: Job
metadata:
  name: test-job
  namespace: core-banking
spec:
  backoffLimit: 0
  template:
    metadata:
      name: test-job
      namespace: yallow
    spec:
      imagePullSecrets:
        - name: docker-registry
      containers:
        - image: "postgres:13.3"
          name: job
          command:
            - sh
            - -c
            - . /vault/secrets/db_secrets.env && psql -v ON_ERROR_STOP=1 -a -f /sql/script.sql
          volumeMounts:
            - name: sql
              mountPath: /sql
          env:
            - name: PGHOST
              value: "yallow.cluster-csh2ya74kut3.eu-west-1.rds.amazonaws.com"
            - name: PGDATABASE
              value: "yallow-client-settings"
            - name: PGDATABASE
              value: "yallow-client-settings"
```
 In the yaml example above, `env` has `PGDATABASE` duplicated, if `kubeconform` could detect such duplicate evars and throw an error it would be useful. `containers` is present in deployment, pod, job and cronjob spec.

If someone  could point me to the part of codebase where we could add the validation I am interested in taking this up and working on it.

Thank you for the amazing kubeconform, it is useful to us 🙇‍♀️
