### ISSUE TITLE
openapi2jsonschema.py not working with missing property field.

### ISSUE THREAD

**Issue by jmcgrath207** [yannh/kubeconform#199]
When using the [ openapi2jsonschema.py ](https://github.com/yannh/kubeconform/blob/master/scripts/openapi2jsonschema.py)  with Json Schema output below, I keep getting a failed check from kubeconform. I believe it might be due to the property field missing. While YAML CRD is pretty empty, It is valid and I can deploy it against our cluster.

Json Schema Output for Kubeconform.
```json
{
  "type": "object",
  "x-kubernetes-preserve-unknown-fields": true
}
```

What I expect
```json
{
  "properties": {
    "apiVersion": {
      "type": "string"
    },
    "kind": {
      "type": "string"
    },
    "metadata": {
      "type": "object"
    },
    "spec": {
...
```

Kubeconform Command.
```bash
kubeconform -summary -kubernetes-version "${version}" -schema-location default -schema-location "${schemas_dir}/{{.ResourceKind}}-stable-{{.ResourceAPIVersion}}.json" -exit-on-error
```

Example CRD

```yaml
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: flyteworkflows.flyte.lyft.com
spec:
  conversion:
    strategy: None
  group: flyte.lyft.com
  names:
    kind: FlyteWorkflow
    listKind: FlyteWorkflowList
    plural: flyteworkflows
    shortNames:
    - fly
    singular: flyteworkflow
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        type: object
        x-kubernetes-preserve-unknown-fields: true
    served: true
    storage: true
```
