### ISSUE TITLE
Unable to use the CRD example schema

### ISSUE THREAD

**Issue by Wazbat** [yannh/kubeconform#211]
I'm trying to validate my kubernetes templates using kubeconform in a github actions workflow, however I get an error in my CI

Here is the step in my build process
```yaml
- uses: docker://ghcr.io/yannh/kubeconform:master
  with:
    entrypoint: '/kubeconform'
    args: >
      -summary -output text
      -schema-location default
      -schema-location 'https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/{{ .Group }}/{{ .ResourceKind }}_{{ .ResourceAPIVersion }}.json'
      manifest-${{ matrix.name }}.yaml"
```
I have copied the url from the README, however I get the following error:
`failed initialising schema location registry: template: tpl:1:64: executing "tpl" at <.Group>: can't evaluate field Group in type struct { NormalizedKubernetesVersion string; StrictSuffix string; ResourceKind string; ResourceAPIVersion string; KindSuffix string }`

It appears that {{.Group}} is not valid as part of the template string? What should I be using there instead?
