### ISSUE TITLE
How to use with envsubst?

### ISSUE THREAD

**Issue by koroldavid** [yannh/kubeconform#226]
Given such config:

```yaml
apiVersion: apps/v1
kind: Deployment
spec:
  replicas: ${REPLICA_COUNT}
  ...
```
Its validation will result in an error:

```
"msg": "For field spec.replicas: Invalid type. Expected: [integer,null], given: string"
```

Technically, `kubeconform` working correctly.
However, in practice, I will replace `${REPLICA_COUNT}` using `envsubst < test-config.yaml`. So I want to ignore it by my CI.

My current workaround is to substitute all `${*}` with null. Write that content to a temporary file. And finally validate it.

Is there any better approach? The ability to ignore a rule per some line might come in handy
