### ISSUE TITLE
Zero exit code on malformed yamls

### ISSUE THREAD

**Issue by mhr3** [yannh/kubeconform#230]
We use kubeconform in our CI, and noticed that a malformatted yaml produces an error to stderr, yet the exit code is 0, which means our CI thinks everything is fine.

The error we get is:
```
...: MalformedYAMLError: yaml: line 26: mapping values are not allowed in this context in File: ./res.yaml
Summary: 0 resource found parsing stdin - Valid: 0, Invalid: 0, Errors: 0, Skipped: 0
% echo $?
0
```

this was with `v0.6.1`

**Comment by yannh** [comment]
Hi, what command line do you use? Any way to reproduce? Thanks!

**Comment by mhr3** [comment]
It was `kubeconform -summary -ignore-missing-schemas`

There was an extra space in an env value:
```
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: LABEL_SELECTOR
               value: key=value
```
