### ISSUE TITLE
Failing on ConfigMap empty key values?

### ISSUE THREAD

**Issue by esn89** [yannh/kubeconform#240]
I have successfully `helm lint`ed and `helm template` some purposefully wrong ConfigMaps, then piping them to `kubeconform`.

As an example I have:

```yaml
apiVersion: v1
data:
  ENDPOINT_NAME: 
  ENDPOINT_TYPE: "https"
kind: ConfigMap
metadata:
  name: weee
  namespace: woo
```

When piped, I get:

```
cat test.yaml | kubeconform -summary -verbose
stdin - ConfigMap weee is valid
Summary: 1 resource found parsing stdin - Valid: 1, Invalid: 0, Errors: 0, Skipped: 0
```

How can I make it fail on empty values?
