### ISSUE TITLE
Schema Recognition issue in kubeconform v0.6.3 and above

### ISSUE THREAD

**Issue by AjanKG** [yannh/kubeconform#247]
Hello,

I am experiencing a schema recognition issue with kubeconform starting from version 0.6.3 and continuing in the latest version 0.6.4. 
The tool fails to recognize the schema for Apigee resources (ApigeeEnvironment and ApigeeOrganization):
- The JSON schema was generated using the latest version of kubeconform/scripts/opeanpi2jsonschema.py (https://github.com/yannh/kubeconform/blob/master/scripts/openapi2jsonschema.py)
- The functionality works as expected in kubeconform version 0.6.2, suggesting a regression in later versions

### **Actual Results:**

kubeconform versions 0.6.3 and 0.6.4 fail to recognize the schema for these resources, resulting in validation error:
```shell
compiled/config-control/apigeeenvironment_apigeeenv-sample.yaml - ApigeeEnvironment apigeeenv-sample failed validation: could not find schema for ApigeeEnvironment
compiled/config-control/apigeeorganization_apigeeorganization-sample.yaml - ApigeeOrganization apigeeorganization-sample failed validation: could not find schema for ApigeeOrganization
``` 

The ApigeeOrganization CRD:
```yml
---
apiVersion: apigee.cnrm.cloud.google.com/v1beta1
kind: ApigeeOrganization
metadata:
  name: apigeeorganization-sample
spec:
  analyticsRegion: us-west1
  authorizedNetworkRef:
    name: apigeeorganization-dep
  displayName: Apigee Organization
  projectRef:
    name: "sample-apigee-ts"
  runtimeType: CLOUD
``` 

### **Expected Results:**
kubeconform should correctly recognize and validate the schema of the given resource, as it did in version 0.6.2
