### ISSUE TITLE
Kubeconform does not report when "metadata.name" is missing

### ISSUE THREAD

**Issue by yogeek** [yannh/kubeconform#286]
```
cat <<EOF | kubeconform -
apiVersion: v1
kind: Pod
metadata:
  names: myapp  # <====== "names" instead of "name"
  labels:
    name: myapp
spec:
  containers:
  - name: myapp
    image: <Image>
EOF
# !!! no error !!!
```

Even if I remove the "name" field entirely, no error in kubeconform... 
```
cat <<EOF | kubeconform -
apiVersion: v1
kind: Pod
metadata:
  # no name field !!!
  labels:
    name: myapp
spec:
  containers:
  - name: myapp
    image: <Image>
EOF
# !!! no error !!!
```

Tested with kubeconform 0.6.6 and 0.6.7 (installed with devbox)

**Comment by wyardley** [comment]
I'm not a maintainer, but it does seem to fail on `metadata.names` if you set `-strict`, though I can confirm there's no warning if you don't set it:

```
% cat <<EOF | kubeconform -strict -verbose -
apiVersion: v1
kind: Pod
metadata:
  names: myapp  # <====== "names" instead of "name"
  labels:
    name: myapp
spec:
  containers:
  - name: myapp
    image: <Image>
EOF
stdin - Pod  is invalid: problem validating schema. Check JSON formatting: jsonschema: '/metadata' does not validate with https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master-standalone-strict/pod-v1.json#/properties/metadata/additionalProperties: additionalProperties 'names' not allowed
```
I see the same behavior that you do where `kubeconform` doesn't seem to error on a missing `metadata.name` field for multiple types of resources.
