### ISSUE TITLE
Annotations and Labels without values are not detected

### ISSUE THREAD

**Issue by chonton** [yannh/kubeconform#287]
For the resource below, I expect kubeconfig to complain about annotation / label values being empty (or null)

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: some-values
  labels:
    some.domain/some-key:
  annotations:
    some.domain/some-key:
data:
  application.yaml: |-
    endpoints:
      service: https://example.com
```

Unfortunately, the ObjectMeta schema does not encode all requirements (or the schema validation package cannot detect missing values).  I suspect that kubeconform would need to separately validate these requirements:

- https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#dns-label-names
-  https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/#syntax-and-character-set
- https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#syntax-and-character-set
- Total annotations size must be < 256KB: 
https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apimachinery/pkg/api/validation/objectmeta.go#L44-L67

Similar to #275, #286, and #240
