### ISSUE TITLE
job envs are failing and should be allowed from valuesFrom.secretKeyRef or valuesFrom.configMapKeyRef

### ISSUE THREAD

**Issue by drduker** [yannh/kubeconform#297]
job envs are failing and should be allowed from valuesFrom.secretKeyRef or valuesFrom.configMapKeyRef

`stdin - Job examplejob is invalid: problem validating schema. Check JSON formatting: jsonschema: '/spec/template/spec/containers/0/env/6' does not validate with https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master-standalone-strict/job-batch-v1.json#/properties/spec/properties/template/properties/spec/properties/containers/items/properties/env/items/additionalProperties: additionalProperties 'secretKeyRef' not allowed`

```
    env:
      - name: example
        value: DBAdmin
      - name: SPRING_DATASOURCE_PASSWORD
        valueFrom:
          secretKeyRef:
            name: example
            key: APP_DB_PASS
      - name: SPECIAL_LEVEL_KEY
        valueFrom:
          configMapKeyRef:
            name: special-config
            key: SPECIAL_LEVEL
```
