### ISSUE TITLE
kubeconform fails for explicit `null` in `nullable` fields

### ISSUE THREAD

**Issue by hojerst** [yannh/kubeconform#310]
kubeconform currently fails when a nullable field is explicitly set to `null`, which just seems wrong. It works, when the field is removed completely.

note: In our workflow we use ArgoCD to apply manifests and ArgoCD behaves differently if a field is explicitly `null` or just unset. So just removing the field is not an option for us.

example:

```plain
❯ kubeconform -schema-location default -schema-location 'https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/{{.Group}}/{{.ResourceKind}}_{{.ResourceAPIVersion}}.json' test.yml
test.yml - Schedule test is invalid: problem validating schema. Check JSON formatting: jsonschema: '/spec/template/includeClusterResources' does not validate with https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/velero.io/schedule_v1.json#/properties/spec/properties/template/properties/includeClusterResources/type: expected boolean, but got null
```

test.yml manifest:

```yaml
apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: test
  namespace: velero
spec:
  schedule: "0 7 * * * "
  template:
    csiSnapshotTimeout: 10m
    includedNamespaces:
    - 'test'
    includedResources:
    - '*'
    includeClusterResources: null
    snapshotVolumes: true
    storageLocation: default
    volumeSnapshotLocations:
        - default
    ttl: 24h0m0s
    defaultVolumesToRestic: false
```
