### ISSUE TITLE
Is this supposed to work?

### ISSUE THREAD

**Issue by FalcoSuessgott** [yannh/kubeconform#313]
Im sorry but is this supposed to work?

```yaml
apiVersion: v1
kind: Service
metafffdata:
  name: svc
spec:
  type: ClusterIP
  invalid: ImAnInvalidField
  true: another one
  ports:
    - port: 9313
      protocol: TCP
      targetPort: 9313
```

```bash
cat svc.yml | kubeconform -summary -schema-location default -verbose
stdin - Service  is valid
Summary: 1 resource found parsing stdin - Valid: 1, Invalid: 0, Errors: 0, Skipped: 0
```
