### ISSUE TITLE
kubeconform doesn't catch some edge cases

### ISSUE THREAD

**Issue by nniehoff-coreweave** [yannh/kubeconform#315]
We validate all of our resources through kubeconform and it works great, however, we just ran in to somewhat of an edge case that I've been able to reproduce.  Kubeconform validates this as well as `kubectl --dry-run=client`, `server` does indeed catch this:

```yaml
apiVersion: v1
data:
  hello: world
kind: ConfigMap
metadata:
  labels:
    invalid: hello"
  name: test
  namespace: default
```

This is an invalid ConfigMap definition and fails to apply `The ConfigMap "test" is invalid: metadata.labels: Invalid value: "hello\"": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',  or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?')`.  I don't think this is a bug in kubeconform as technically it's valid yaml/json but it's definitely and invalid resource and I'm curious how we should try to catch this.
