### ISSUE TITLE
Not catching a missing attribute in VirtualServices

### ISSUE THREAD

**Issue by AndresPinerosZen** [yannh/kubeconform#317]
I'm using this example VirtualService:

```
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  annotations:
    company.com/local-port: "8080"
  labels:
    app.kubernetes.io/instance: my-app
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: my-app
    app.kubernetes.io/part-of: my-app
    argocd.argoproj.io/instance: my-app
    helm.sh/chart: my-app-1.0.0
    company.com/portfolio: ""
  name: my-app
  namespace: my-app
spec:
  http:
  - match:
    - uri:
        prefix: /my-app/
    # name: my-app  <--------------- Doesn't care if this attribute exists.
    route:
    - destination:
        host: my-app
        port:
          number: 80
        subset: my-app
```

I'm using this command:
```
cat file.yaml | kubeconform -summary --ignore-missing-schemas -schema-location default -schema-location https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/{{.Group}}/{{.ResourceKind}}_{{.ResourceAPIVersion}}.json
```

Which should be using this schema:
https://raw.githubusercontent.com/datreeio/CRDs-catalog/refs/heads/main/networking.istio.io/virtualservice_v1beta1.json

I can see the name attribute in that schema.

It says:
```
Summary: 1 resource found parsing stdin - Valid: 1, Invalid: 0, Errors: 0, Skipped: 0
```
