### ISSUE TITLE
Support for inline schema references

### ISSUE THREAD

**Issue by stackane** [yannh/kubeconform#318]
As a developer, I want kubeconform to pick up inline schema configuration, so I don't have to provide schemas in multiple locations and can keep the schema configuration together with the manifests they belong to.

I am using the [yaml-language-server](https://github.com/redhat-developer/yaml-language-server) in my favorite IDE to assist me in editing specific manifests and it supports providing schema locations inline, e.g.:

```yaml
# yaml-language-server: $schema=https://github.com/datreeio/CRDs-catalog/raw/refs/heads/main/networking.istio.io/sidecar_v1beta1.json
apiVersion: networking.istio.io/v1beta1
kind: Sidecar
metadata:
  name: default
spec:
  egress:
    - hosts:
        - default/kubernetes.default.svc.cluster.local
        - ...
```

Now I want to have kubeconform pick up this info and behave as follows:
1. if no such inline schema is specified, use the one configured at command line invocation (`-schema-location` option) → retain existing behavior
2. if an inline schema is specified, validate the YAML document to the provided schema, effectively overriding command line options
