### ISSUE TITLE
kubeconform is rejecting metadata.namespace on a CRD that allows them

### ISSUE THREAD

**Issue by terite** [yannh/kubeconform#319]
I'm using kubeconform to validate a namespace-scoped custom resource. The CRD has a schema that validates `metadata.name`. kubeconform correctly validates `metadata.name`, but unexpectedly says that `metadata.namespace` is not allowed, even though this is a `scope: Namespaced` CRD.

I see that kubeconform [doesn't intend](https://github.com/yannh/kubeconform?tab=readme-ov-file#Limits-of-Kubeconform-validation) to do _additional_ Non-OpenAPI validations, but how do you feel about relaxing a case where kubeconform is being overly strict?

### Context:

Here's my `ServiceDirectoryRegistrationPolicy`:
```yaml
apiVersion: networking.gke.io/v1alpha1
kind: ServiceDirectoryRegistrationPolicy
metadata:
  name: some-invalid-name
  namespace: primary
```

Google documents how to use this custom resource here: https://cloud.google.com/service-directory/docs/configuring-sd-for-gke#configure_a_servicedirectoryregistrationpolicy

When I validate that object with `kubectl apply --dry-run=server` I get the following error as expected

```
The ServiceDirectoryRegistrationPolicy "some-invalid-name" is invalid: metadata.name: Unsupported value: "some-invalid-name": supported values: "default"
```

When I validate with kubeconform I get the expected name error, but also get an unexpected error saying that namespace is not allowed.

```
      "filename": "<snip>",                                                                              
      "kind": "ServiceDirectoryRegistrationPolicy",                                                                                                          
      "name": "some-invalid-name",                                                                                                                           
      "version": "networking.gke.io/v1alpha1",                                                                                                               
      "status": "statusInvalid",                                                                                                                             
      "msg": "problem validating schema. Check JSON formatting: jsonschema: '/metadata/name' does not validate with file:///Users/terite/.datree/crdSchemas/n
etworking.gke.io/servicedirectoryregistrationpolicy_v1alpha1.json#/properties/metadata/properties/name/enum: value must be \"default\"",                     
      "validationErrors": [                                                                                                                                  
        {                                                                                                                                                    
          "path": "/metadata/name",                                                                                                                          
          "msg": "value must be \"default\""                                                                                                                 
        },                                                                                                                                                   
        {                                                                                                                                                    
          "path": "/metadata",                                                                                                                               
          "msg": "additionalProperties 'namespace' not allowed"                                                                                              
        }                                                                                                                                                    
      ]  
```

For context, here is the relevant part of the CRD:
```yaml
spec:
  # ...snip...
  scope: Namespaced
  versions:
  - # ...snip...
    schema:
      openAPIV3Schema:
        description: ServiceDirectoryRegistrationPolicy defines the Schema of the
          ServiceDirectoryRegistrationPolicy CR.
        properties:
          # ...snip...
          metadata:
            properties:
              name:
                enum:
                - default
                type: string
            type: object
          # ...snip...

```
Here's the full CRD if you find it helpful, or if I snipped too much: https://gist.github.com/terite/3d60f14ac5ef9893a2573e79310999d0
