### ISSUE TITLE
Support for inline directive comments

### ISSUE THREAD

**Issue by Kariton** [yannh/kubeconform#321]
Hey,

first of all: thanks for this incredible tool!

kubeconform is so useful but when using flux templates it would be handy
to utilize inline directive comments to selectively overwrite behavior in contrast to excluding the entire file.

example usecase (snipped) from kustomize component:
```yaml
---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/postgres-operator.crunchydata.com/postgrescluster_v1beta1.json
apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: &name ${APP}
spec:
  users:
    # Superuser
    - name: postgres
      databases: ["postgres"]
      options: SUPERUSER
      password:
        type: AlphaNumeric
    # Applications
    - name: ${USERNAME:=${APP}}
      databases: ${DATABASES:=["${APP}"]}
      password:
        type: AlphaNumeric
```

yields:
> components/postgres/cluster.yaml - PostgresCluster ${APP} is invalid: problem validating schema. Check JSON formatting: jsonschema: '/spec/users/1/databases' does not validate with https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master-standalone-strict/postgrescluster-postgres-operator-v1beta1.json#/properties/spec/properties/users/items/properties/databases/type: expected array, but got string

i mean something like this:
```
spec:
  users:
    - name: ${USERNAME:=${APP}}
      databases: ${DATABASES:=["${APP}"]} # kubeconform type=array
```
so `type` is referencing the json key. or overwriting `pattern=(.*)` etc.
