### ISSUE TITLE
Dockerfile for other CI providers

### ISSUE THREAD

**Issue by MaxRink** [yannh/kubeconform#47]
The Dockerfile currently doesnt seem to work on GitLab CI for example, as GL-CI expects to be able to oppen up a shell in the container and execute the cmd that way.
Just specifying entrypoint and args isnt allowed by gitlab and treatet as an invalid config.
For the dokcer image to work properly with Gitlab CI there would need to be a shell inside the container, although the entrypoint could just remain as it is right now.

**Comment by yannh** [comment]
Hi Max, I understand the need - though using a different base image also means I'd have to keep it up to date. What do you need, just a Dockerfile or also a full docker image hosted somewhere?

**Comment by aexvir** [comment]
just leaving a small comment here, as we're maintaining our [own `kubconform` image](https://github.com/kiwicom/dockerfiles/releases/tag/kubeconform-0.4.8) that we're using in GitLab CI

you can either just call `kubeconform`
```yaml
kubeconform:
  stage: analysis
  image: kiwicom/kubeconform
  cache:
    key: "kubeconform-${CI_COMMIT_REF_SLUG}"
    paths:
      - .cache/
  script:
    - kubeconform -cache .cache -summary -exit-on-error k8s
```

or use [our `analyse` script](https://github.com/kiwicom/dockerfiles/blob/master/kubeconform/analyse.py) which iterates and renders all the kustomizations before running `kubeconform`
```yaml
kubeconform:
  stage: analysis
  image: kiwicom/kubeconform
  cache:
    key: "kubeconform-${CI_COMMIT_REF_SLUG}"
    paths:
      - .cache/
  variables:
    KUBECONFORM_CACHE: .cache
  script:
    - analyse k8s
```

or feel free to just take [as inspiration](https://github.com/kiwicom/dockerfiles/blob/master/kubeconform/Dockerfile) for anything else 😅
