### ISSUE TITLE
Validating special helm values crd using values.schema.json 

### ISSUE THREAD

**Issue by tarioch** [yannh/kubeconform#77]
I really like kubeconform and now with it, I'm able to validate CRDs very nicely.

I'm heavily relying on gitops/flux for managing my clusters and it's really nice to be able to do a lot of the validation locally with a pre-commit hook :)

I'm using flux2 and this heavily relies on a special CRD that looks like this

```yaml
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: foo
  namespace: default
spec:
  interval: 1h
  releaseName: foo
  chart:
    spec:
      chart: foo
      version: 5.0.1
  values:
    ingress:
      main:
        enabled: true
        hosts:
          - host: foo.example.tld
            paths:
              - path: /
```

Now the CRD has a nice schema for everything except the values block (as this is naturally depending on the chart). 

helm3 supports Values.Schema.Json for a helm chart, so I'm wondering if there could be a way to make actually use of this for validating the values section. I'm aware that this might be a very special use-case but I think for other users of flux (or similar systems that depend on a CRD for managing helm releases) this could be useful. 

Any idea if kubeconform could be extended to support this usecase? Or would there be better approach to do this?
