### ISSUE TITLE
KubeConform does not give error on invalid namespace names

### ISSUE THREAD

**Issue by Moulick** [yannh/kubeconform#82]
Kubeconform does not give an error when fed a invalid namespace as below
```yaml
apiVersion: v1
kind: Namespace
metadata:
  name: .hello
```
```bash
❯ kubeconform -verbose -strict namespace.yaml
namespace.yaml - Namespace .hello is valid
```
Version: 0.4.12

This is same as in KubeVal https://github.com/instrumenta/kubeval/issues/321
